-- The canonical production schema is versioned as a migration:
-- supabase/migrations/202607180001_phase1_foundation.sql
--
-- Apply it with the Supabase CLI (`supabase db push`) or paste the complete
-- migration into the Supabase SQL Editor once. Do not maintain a second,
-- divergent schema in this file.
