"use client";
import { useState } from "react";
import { Save, SlidersHorizontal } from "lucide-react";
import type { BrandProfile } from "@/lib/types";

const lines=(value:string)=>value.split("\n").map(x=>x.trim()).filter(Boolean);
export default function BrandProfilePanel({initial,onSaved}:{initial:BrandProfile;onSaved:(profile:BrandProfile)=>void}) {
  const [profile,setProfile]=useState(initial),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  const list=(key:"voice"|"audiences"|"approvedCtas"|"prohibitedClaims",value:string)=>setProfile(p=>({...p,[key]:lines(value)}));
  async function save(){setSaving(true);setMessage("");try{const response=await fetch("/api/brand-profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});const data=await response.json();if(!response.ok)throw new Error(data.error);onSaved(profile);setMessage("Brand rules saved and will be used for every campaign.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to save brand rules.");}finally{setSaving(false)}}
  return <section className="panel brand-profile-panel"><div className="brand-profile-heading"><div><div className="eyebrow">PHASE 1 · BRAND INTELLIGENCE</div><h2>Your brand rules</h2><p>Saved voice, audience, CTA and compliance rules guide every platform differently.</p></div><button type="button" className="icon-action" onClick={()=>setOpen(v=>!v)}><SlidersHorizontal size={17}/>{open?"Close":"Edit rules"}</button></div>{open&&<div className="brand-profile-form"><label>STORE NAME<input value={profile.storeName} onChange={e=>setProfile(p=>({...p,storeName:e.target.value}))}/></label><label>WEBSITE<input value={profile.websiteUrl} onChange={e=>setProfile(p=>({...p,websiteUrl:e.target.value}))}/></label><label>BRAND VOICE — ONE PER LINE<textarea value={profile.voice.join("\n")} onChange={e=>list("voice",e.target.value)}/></label><label>AUDIENCES — ONE PER LINE<textarea value={profile.audiences.join("\n")} onChange={e=>list("audiences",e.target.value)}/></label><label>APPROVED CTAS — ONE PER LINE<textarea value={profile.approvedCtas.join("\n")} onChange={e=>list("approvedCtas",e.target.value)}/></label><label>PROHIBITED CLAIMS — ONE PER LINE<textarea value={profile.prohibitedClaims.join("\n")} onChange={e=>list("prohibitedClaims",e.target.value)}/></label><button type="button" className="brand-save" onClick={save} disabled={saving}><Save size={16}/>{saving?"Saving…":"Save brand rules"}</button>{message&&<div className="status">{message}</div>}</div>}</section>;
}
