"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{Archive,CalendarDays,ChevronLeft,ChevronRight,Clock3,ExternalLink,RefreshCw,Trash2}from"lucide-react";

type Campaign={id:string;name:string;status:string;created_at:string;scheduled_for:string|null;published_at:string|null;external_post_url:string|null;product_snapshot:{title?:string};settings:{image_url?:string};variation:{content:{image_url?:string}}|null};
const labels:Record<string,string>={ready_for_review:"Review",approved:"Approved",scheduled:"Scheduled",published:"Published",changes_requested:"Changes",partially_failed:"Attention",publishing:"Publishing"};
const dateKey=(value:string|Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dubai",year:"numeric",month:"2-digit",day:"2-digit"}).format(typeof value==="string"?new Date(value):value);
const eventDate=(item:Campaign)=>item.scheduled_for||item.published_at||item.created_at;

export default function CampaignCalendar(){
  const[items,setItems]=useState<Campaign[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1)});
  const load=useCallback(async()=>{setMessage("");try{const response=await fetch("/api/meta/campaigns",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data.campaigns||[])}catch(error){setMessage(error instanceof Error?error.message:"Unable to load the campaign calendar.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
  const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-first.getDay());return Array.from({length:42},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day})},[month]);
  const grouped=useMemo(()=>{const map=new Map<string,Campaign[]>();for(const item of items){const key=dateKey(eventDate(item));map.set(key,[...(map.get(key)||[]),item])}return map},[items]);
  const counts=items.reduce((sum,item)=>({...sum,[item.status]:(sum[item.status]||0)+1}),{} as Record<string,number>),today=dateKey(new Date());
  function openQueue(){document.getElementById("content-review-queue")?.scrollIntoView({behavior:"smooth",block:"start"})}
  async function archive(item:Campaign){setBusy(item.id);setMessage("");try{const response=await fetch("/api/meta/campaigns",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"archive",campaignId:item.id})}),data=await response.json();if(!response.ok)throw new Error(data.error);await load()}catch(error){setMessage(error instanceof Error?error.message:"Unable to archive campaign.")}finally{setBusy("")}}
  async function remove(item:Campaign){if(!window.confirm(`Permanently delete “${item.product_snapshot?.title||item.name}” and its local campaign data? Published social posts will remain live.`))return;setBusy(item.id);setMessage("");try{const response=await fetch(`/api/meta/campaigns?campaignId=${encodeURIComponent(item.id)}`,{method:"DELETE"}),data=await response.json();if(!response.ok)throw new Error(data.error);await load()}catch(error){setMessage(error instanceof Error?error.message:"Unable to delete campaign.")}finally{setBusy("")}}
  return <section className="panel calendar-panel" id="campaign-calendar">
    <div className="calendar-heading"><div><div className="eyebrow">PHASE 6 · CAMPAIGN ORCHESTRATION</div><h2><CalendarDays size={25}/> Plan the marketing calendar</h2><p>See active campaigns in UAE time. Archive old work or delete failed and unwanted campaigns.</p></div><div className="calendar-heading-actions"><button type="button" className="ui-action" onClick={openQueue}>Open Review Queue</button><button type="button" className="ui-action" onClick={()=>{setLoading(true);void load()}} disabled={loading}><RefreshCw size={15} className={loading?"spin":""}/>{loading?"Refreshing…":"Refresh"}</button></div></div>
    {message&&<div className="status error">{message}</div>}
    <div className="calendar-summary"><Summary label="Needs review" value={(counts.ready_for_review||0)+(counts.changes_requested||0)}/><Summary label="Approved" value={counts.approved||0}/><Summary label="Scheduled" value={counts.scheduled||0}/><Summary label="Published" value={counts.published||0}/></div>
    <div className="calendar-toolbar"><button type="button" onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()-1,1))} aria-label="Previous month"><ChevronLeft/></button><h3>{month.toLocaleDateString("en-AE",{month:"long",year:"numeric"})}</h3><button type="button" onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()+1,1))} aria-label="Next month"><ChevronRight/></button><button type="button" className="calendar-today" onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1))}}>Today</button></div>
    <div className="calendar-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><span key={day}>{day}</span>)}</div>
    <div className="calendar-grid">{days.map(day=>{const key=dateKey(day),events=grouped.get(key)||[],outside=day.getMonth()!==month.getMonth();return <article key={key} className={`${outside?"outside":""} ${key===today?"today":""}`}><header><span>{day.getDate()}</span>{events.length>0&&<small>{events.length}</small>}</header><div>{events.slice(0,3).map(item=><CalendarEvent key={item.id} item={item} busy={busy===item.id} archive={archive} remove={remove}/>)}{events.length>3&&<button type="button" className="calendar-more" onClick={openQueue}>+{events.length-3} more</button>}</div></article>})}</div>
    <div className="calendar-legend"><span className="ready_for_review">Review</span><span className="approved">Approved</span><span className="scheduled">Scheduled</span><span className="published">Published</span><small><Clock3 size={13}/> All times use Asia/Dubai.</small></div>
  </section>
}

function Summary({label,value}:{label:string;value:number}){return <div><strong>{value}</strong><span>{label}</span></div>}
function CalendarEvent({item,busy,archive,remove}:{item:Campaign;busy:boolean;archive:(item:Campaign)=>void;remove:(item:Campaign)=>void}){
  const title=item.product_snapshot?.title||item.name,image=item.variation?.content.image_url||item.settings?.image_url;
  return <div className={`calendar-event ${item.status}`} title={title}>{image&&<img src={image} alt=""/>}<span><b>{title}</b><small>{labels[item.status]||item.status.replaceAll("_"," ")}{item.scheduled_for?` · ${new Date(item.scheduled_for).toLocaleTimeString("en-AE",{timeZone:"Asia/Dubai",hour:"2-digit",minute:"2-digit"})}`:""}</small></span><div className="calendar-event-actions">{item.external_post_url&&<a href={item.external_post_url} target="_blank" rel="noreferrer" aria-label="Open published post"><ExternalLink size={12}/></a>}<button type="button" onClick={()=>archive(item)} disabled={busy} aria-label="Archive campaign"><Archive size={12}/></button><button type="button" onClick={()=>remove(item)} disabled={busy} aria-label="Delete campaign"><Trash2 size={12}/></button></div></div>
}
