"use client";
import {useEffect,useRef} from "react";
import type {CampaignCopy,ProductData} from "@/lib/types";
import {brand} from "@/lib/brand";

function wrap(c:CanvasRenderingContext2D,text:string,max:number){const words=text.split(" "),lines:string[]=[];let line="";for(const word of words){const test=`${line} ${word}`.trim();if(c.measureText(test).width>max&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}

export default function CreativeCanvas({label,width,height,product,campaign,background}:{label:string;width:number;height:number;product:ProductData;campaign:CampaignCopy;background?:string}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas)return;canvas.width=width;canvas.height=height;const c=canvas.getContext("2d");if(!c)return;(async()=>{c.fillStyle=brand.palette.ivory;c.fillRect(0,0,width,height);if(background){const bg=new Image();bg.src=background;await bg.decode().catch(()=>{});if(bg.naturalWidth){const s=Math.max(width/bg.naturalWidth,height/bg.naturalHeight);c.globalAlpha=.82;c.drawImage(bg,(width-bg.naturalWidth*s)/2,(height-bg.naturalHeight*s)/2,bg.naturalWidth*s,bg.naturalHeight*s);c.globalAlpha=1}}if(product.images[0]){const image=new Image();image.crossOrigin="anonymous";image.src=product.images[0];await image.decode().catch(()=>{});if(image.naturalWidth){const area=height*.60,s=Math.min(width*.82/image.naturalWidth,area/image.naturalHeight),dw=image.naturalWidth*s,dh=image.naturalHeight*s;c.shadowColor="rgba(24,24,24,.16)";c.shadowBlur=25;c.drawImage(image,(width-dw)/2,height*.06+(area-dh)/2,dw,dh);c.shadowBlur=0}}const p=width*.07,y=height*.70;c.fillStyle=brand.palette.charcoal;c.font=`600 ${width*.031}px Arial`;c.fillText("K A V I A",p,y);c.font=`700 ${width*.057}px Georgia`;const lines=wrap(c,campaign.headline.toUpperCase(),width-p*2);lines.forEach((line,n)=>c.fillText(line,p,y+width*.075+n*width*.063));c.font=`500 ${width*.026}px Arial`;c.fillStyle="rgba(24,24,24,.76)";const sub=wrap(c,campaign.subheadline,width-p*2),sy=y+width*.075+lines.length*width*.063+width*.02;sub.slice(0,2).forEach((line,n)=>c.fillText(line,p,sy+n*width*.035));const by=Math.min(height-width*.12,sy+sub.length*width*.035+width*.04);c.fillStyle=brand.palette.charcoal;c.beginPath();c.roundRect(p,by,width*.31,width*.075,width*.04);c.fill();c.fillStyle="#fff";c.font=`700 ${width*.023}px Arial`;c.fillText(campaign.cta,p+width*.035,by+width*.047)})()},[width,height,product,campaign,background]);
  const download=()=>{const anchor=document.createElement("a");anchor.download=`${product.handle}-${label.toLowerCase().replace(/\s+/g,"-")}.png`;anchor.href=ref.current!.toDataURL("image/png");anchor.click()};
  return <div className="creative-card"><canvas ref={ref}/><div className="creative-tools"><strong>{label} · {width}×{height}</strong><div><a className="creative-cta-preview" href={product.url} target="_blank" rel="noreferrer">{campaign.cta} ↗</a><button type="button" onClick={download}>Download PNG</button></div></div><small className="canvas-note">CTA inside the image is artwork. Use the link above to test the destination.</small></div>;
}
