"use client";
import { useEffect, useState } from "react";
import { CalendarClock, Facebook, Instagram, ShieldCheck } from "lucide-react";
type Status={configured:boolean;connected:boolean;connection:{accountName:string}|null;checks:{appId:boolean;appSecret:boolean;encryptionKey:boolean};callbackUrl:string;requiredPermissions:string[]};
export default function MetaPublishingPanel(){
  const[data,setData]=useState<Status|null>(null),[publishing,setPublishing]=useState(false),[publishMessage,setPublishMessage]=useState("");
  useEffect(()=>{fetch("/api/meta/status",{cache:"no-store"}).then(r=>r.json()).then(setData).catch(()=>setData(null))},[]);
  async function publishDue(){setPublishing(true);setPublishMessage("");try{const response=await fetch("/api/meta/publish-due",{method:"POST"}),result=await response.json();if(!response.ok)throw new Error(result.error);setPublishMessage(result.processed?`${result.processed} due post${result.processed===1?"":"s"} processed.`:"No approved posts are due yet.");}catch(error){setPublishMessage(error instanceof Error?error.message:"Unable to run publishing worker.")}finally{setPublishing(false)}}
  return <section className="panel meta-panel" id="meta-publishing"><div className="meta-heading"><div><div className="eyebrow">PHASE 4 · META PUBLISHING</div><h2><Instagram size={24}/><Facebook size={24}/> Connect, approve and schedule</h2><p>Publishing stays approval-first. Nothing posts until you explicitly approve it.</p></div><span className={`readiness ${data?.configured?"ready":"setup"}`}>{data?.connected?<><ShieldCheck size={16}/> @{data.connection?.accountName} connected</>:data?.configured?<><ShieldCheck size={16}/> Ready to connect</>:"Setup required"}</span></div>{data&&!data.configured&&<div className="meta-setup"><h3>Instagram connection prerequisites</h3><div className="check-grid"><span className={data.checks.appId?"done":""}>INSTAGRAM_APP_ID</span><span className={data.checks.appSecret?"done":""}>INSTAGRAM_APP_SECRET</span><span className={data.checks.encryptionKey?"done":""}>TOKEN ENCRYPTION KEY</span></div><label>OAuth callback URL<code>{data.callbackUrl}</code></label><p className="permission-note">Permissions: {data.requiredPermissions.join(", ")}</p></div>}{data?.configured&&!data.connected&&<div className="meta-ready"><CalendarClock size={20}/><div><strong>Credentials detected</strong><p>Authorize the Instagram Professional account you want this workspace to manage.</p></div><a className="meta-connect" href="/api/meta/connect">Connect Instagram</a></div>}{data?.connected&&<><div className="meta-ready"><ShieldCheck size={20}/><div><strong>Instagram connected securely</strong><p>Only approved posts whose scheduled UAE time has arrived can be published.</p></div><button type="button" className="ui-action" onClick={publishDue} disabled={publishing}>{publishing?"Publishing…":"Publish Due Posts Now"}</button></div>{publishMessage&&<div className="status">{publishMessage}</div>}</>}</section>
}
