"use client";
import{useCallback,useEffect,useMemo,useState}from"react";
import{BarChart3,ExternalLink,RefreshCw,Sparkles,TrendingUp}from"lucide-react";
type Metric={campaign_id:string;views:number;reach:number;likes:number;comments:number;saves:number;shares:number;total_interactions:number;engagement_rate:number;captured_at:string;campaigns:{name?:string;external_post_url?:string;product_snapshot?:{title?:string};published_at?:string}|null};
const number=(value:number)=>new Intl.NumberFormat("en",{notation:value>9999?"compact":"standard",maximumFractionDigits:1}).format(value||0);
export default function PerformanceIntelligence(){
  const[metrics,setMetrics]=useState<Metric[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[setupRequired,setSetupRequired]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/meta/insights",{cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error);setMetrics(data.metrics||[]);setSetupRequired(Boolean(data.setupRequired))}catch(error){setMessage(error instanceof Error?error.message:"Unable to load performance data.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
  async function sync(){setSyncing(true);setMessage("");try{const response=await fetch("/api/meta/insights",{method:"POST"}),data=await response.json();if(!response.ok)throw new Error(data.reconnectRequired?`${data.error} Add Instagram Insights permission in Meta, then reconnect Instagram.`:data.error);setMessage(data.message||`${data.synced} published post${data.synced===1?"":"s"} updated.`);await load()}catch(error){setMessage(error instanceof Error?error.message:"Performance sync failed.")}finally{setSyncing(false)}}
  const totals=useMemo(()=>metrics.reduce((sum,item)=>({views:sum.views+Number(item.views),reach:sum.reach+Number(item.reach),interactions:sum.interactions+Number(item.total_interactions),saves:sum.saves+Number(item.saves),shares:sum.shares+Number(item.shares)}),{views:0,reach:0,interactions:0,saves:0,shares:0}),[metrics]);
  const engagement=totals.reach?(totals.interactions/totals.reach)*100:0,ranked=[...metrics].sort((a,b)=>Number(b.engagement_rate)-Number(a.engagement_rate)),best=ranked[0];
  const recommendation=!metrics.length?"Publish and sync at least two posts to unlock evidence-based creative recommendations.":metrics.length===1?"This is your baseline. Publish the next creative with a different visual concept so the agent can compare performance.":best&&Number(best.engagement_rate)>engagement?`Reuse the visual direction from “${best.campaigns?.product_snapshot?.title||best.campaigns?.name||"your top post"}”; it currently leads on engagement rate.`:"Test a stronger first-frame product focus and a clearer save-worthy benefit in the next creative.";
  return <section className="panel intelligence-panel" id="performance-intelligence"><div className="intelligence-heading"><div><div className="eyebrow">PHASE 5 · PERFORMANCE INTELLIGENCE</div><h2><BarChart3 size={25}/> Measure, learn and improve</h2><p>Compare published creatives using Instagram results and turn performance into the next approved campaign brief.</p></div><button type="button" className="ui-action intelligence-sync" onClick={sync} disabled={syncing||setupRequired}><RefreshCw size={16} className={syncing?"spin":""}/>{syncing?"Syncing…":"Sync Instagram Results"}</button></div>{setupRequired&&<div className="intelligence-setup"><strong>One-time database setup required</strong><span>Run migration 202607190007_performance_intelligence.sql in Supabase, then refresh this page.</span></div>}{message&&<div className="status">{message}</div>}<div className="metric-grid"><MetricCard label="Views" value={loading?"—":number(totals.views)}/><MetricCard label="Reach" value={loading?"—":number(totals.reach)}/><MetricCard label="Interactions" value={loading?"—":number(totals.interactions)}/><MetricCard label="Engagement rate" value={loading?"—":`${engagement.toFixed(2)}%`}/><MetricCard label="Saves" value={loading?"—":number(totals.saves)}/><MetricCard label="Shares" value={loading?"—":number(totals.shares)}/></div><div className="intelligence-lower"><div className="recommendation-card"><Sparkles size={20}/><div><span>AI CREATIVE DIRECTOR</span><strong>{recommendation}</strong><small>Recommendations remain advisory. Nothing is regenerated or published without your approval.</small></div></div><div className="performance-list"><h3><TrendingUp size={18}/> Published creative ranking</h3>{!loading&&!ranked.length?<p>No Instagram results synced yet.</p>:ranked.map((item,index)=><article key={item.campaign_id}><b>#{index+1}</b><div><strong>{item.campaigns?.product_snapshot?.title||item.campaigns?.name||"Instagram campaign"}</strong><small>{number(item.reach)} reach · {number(item.total_interactions)} interactions · {Number(item.engagement_rate).toFixed(2)}%</small></div>{item.campaigns?.external_post_url&&<a href={item.campaigns.external_post_url} target="_blank" rel="noreferrer" aria-label="Open Instagram post"><ExternalLink size={16}/></a>}</article>)}</div></div></section>
}
function MetricCard({label,value}:{label:string;value:string}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong></div>}
