"use client";
import { useState } from "react";
import { CalendarClock, CheckCircle2, Save } from "lucide-react";
import type { CampaignCopy, ProductData } from "@/lib/types";

type Draft = { id: string; variationId: string };
export default function PublishingApprovalPanel({ product, campaign }: { product: ProductData; campaign: CampaignCopy }) {
  const [caption, setCaption] = useState(`${campaign.instagramCaption}\n\n${campaign.instagramHashtags.join(" ")}`), [draft, setDraft] = useState<Draft | null>(null), [scheduledFor, setScheduledFor] = useState("");
  const [state, setState] = useState<"editing" | "saving" | "review" | "approving" | "approved" | "scheduling" | "scheduled">("editing"), [message, setMessage] = useState("");
  async function call(method: "POST" | "PATCH", body: unknown) { const response = await fetch("/api/meta/campaigns", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), data = await response.json(); if (!response.ok) throw new Error(data.error || "Publishing action failed."); return data; }
  async function saveDraft() { setState("saving"); setMessage(""); try { const data = await call("POST", { product, caption, imageUrl: product.images[0] }); setDraft({ id: data.campaign.id, variationId: data.campaign.variationId }); setState("review"); setMessage("Draft saved. Review the final caption and image before approval."); } catch (error) { setState("editing"); setMessage(error instanceof Error ? error.message : "Unable to save draft."); } }
  async function approve() { if (!draft) return; setState("approving"); try { await call("PATCH", { action: "approve", campaignId: draft.id, variationId: draft.variationId }); setState("approved"); setMessage("Approved ✓ This still has not been published."); } catch (error) { setState("review"); setMessage(error instanceof Error ? error.message : "Unable to approve."); } }
  async function schedule() { if (!draft) return; setState("scheduling"); try { const iso = new Date(`${scheduledFor}:00+04:00`).toISOString(); await call("PATCH", { action: "schedule", campaignId: draft.id, variationId: draft.variationId, scheduledFor: iso }); setState("scheduled"); setMessage(`Scheduled ✓ for ${scheduledFor.replace("T", " ")} UAE time. Nothing posts until the publishing worker is enabled.`); } catch (error) { setState("approved"); setMessage(error instanceof Error ? error.message : "Unable to schedule."); } }
  return <section className="publishing-approval"><div className="publishing-title"><div><span>INSTAGRAM APPROVAL</span><h3>Review the final post</h3></div><strong className={`publishing-state ${state}`}>{state === "review" ? "READY FOR REVIEW" : state === "saving" ? "SAVING…" : state === "approving" ? "APPROVING…" : state === "scheduling" ? "SCHEDULING…" : state.toUpperCase()}</strong></div><div className="publishing-preview"><img src={product.images[0]} alt={product.title}/><label>FINAL INSTAGRAM CAPTION<textarea value={caption} onChange={event => setCaption(event.target.value)} disabled={state !== "editing"}/><small>{caption.length}/2,200 characters</small></label></div><div className="publishing-actions">{!draft && <button type="button" className="ui-action" onClick={saveDraft} disabled={state === "saving" || !caption.trim()}><Save size={16}/>{state === "saving" ? "Saving…" : "Save Draft"}</button>}{(state === "review" || state === "approving") && <button type="button" className="ui-action approve" onClick={approve} disabled={state === "approving"}><CheckCircle2 size={16}/>{state === "approving" ? "Approving…" : "Approve Instagram Post"}</button>}{(state === "approved" || state === "scheduling") && <><label>UAE DATE & TIME<input type="datetime-local" value={scheduledFor} onChange={event => setScheduledFor(event.target.value)} disabled={state === "scheduling"}/></label><button type="button" className="ui-action" onClick={schedule} disabled={!scheduledFor || state === "scheduling"}><CalendarClock size={16}/>{state === "scheduling" ? "Scheduling…" : "Schedule"}</button></>}{state === "scheduled" && <button type="button" className="ui-action action-complete" disabled><CheckCircle2 size={16}/>Scheduled ✓</button>}</div>{message && <p className="publishing-message">{message}</p>}</section>;
}
