"use client";
import { useEffect,useMemo,useState } from "react";
import { Download,Film,Mic2,Play,Sparkles } from "lucide-react";
import type { CampaignCopy,ProductData } from "@/lib/types";
type Props={product:ProductData;campaign:CampaignCopy;background?:string};
type ScriptOption={name:string;hook:string;script:string};
const voices=[{value:"coral",label:"Coral · warm"},{value:"marin",label:"Marin · polished"},{value:"cedar",label:"Cedar · confident"},{value:"shimmer",label:"Shimmer · bright"}];
const wait=(ms:number)=>new Promise(resolve=>window.setTimeout(resolve,ms));
function lines(value:unknown){if(Array.isArray(value))return value.map(String).filter(Boolean);return String(value||"").split(/\n+|\. /).map(item=>item.trim()).filter(Boolean)}
function fallbacks(product:ProductData,campaign:CampaignCopy):ScriptOption[]{const detail=lines(campaign.reelScript).join(". "),cta=campaign.cta||"Shop now";return[{name:"Product Reveal",hook:campaign.reelHook||`Meet ${product.title}.`,script:[campaign.reelHook||`Meet ${product.title}.`,detail,campaign.subheadline,`${cta} and discover it today.`].filter(Boolean).join(" ")},{name:"Problem to Desire",hook:"Your next favourite might be closer than you think.",script:`Your next favourite might be closer than you think. Meet ${product.title}. ${campaign.subheadline} ${cta} to see every available detail.`},{name:"Lifestyle Story",hook:"One product, one effortless new direction.",script:`One product can change the direction of an everyday moment. Discover ${product.title}. ${campaign.subheadline} ${cta} when you are ready to make it yours.`},{name:"Direct Response",hook:`Stop scrolling—look closer at ${product.title}.`,script:`Stop scrolling and take a closer look at ${product.title}. ${detail||campaign.subheadline} Explore the current details and available options now. ${cta}.`}]}

export default function VideoProductionStudio({product,campaign,background}:Props){
 const initial=useMemo(()=>fallbacks(product,campaign),[product,campaign]);
 const[options,setOptions]=useState(initial),[selected,setSelected]=useState(0),[script,setScript]=useState(initial[0].script),[loadingScripts,setLoadingScripts]=useState(true);
 const[voice,setVoice]=useState("coral"),[audioUrl,setAudioUrl]=useState(""),[videoUrl,setVideoUrl]=useState(""),[jobId,setJobId]=useState("");
 const[message,setMessage]=useState(""),[generatingVoice,setGeneratingVoice]=useState(false),[generatingVideo,setGeneratingVideo]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{let active=true;(async()=>{try{const response=await fetch("/api/video-scripts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,campaign})}),data=await response.json();if(active&&response.ok&&Array.isArray(data.scripts)&&data.scripts.length){setOptions(data.scripts);setSelected(0);setScript(data.scripts[0].script)}}finally{if(active)setLoadingScripts(false)}})();return()=>{active=false}},[product,campaign]);
 function clearAssets(){if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl("");setVideoUrl("");setJobId("");setProgress(0)}
 async function generateVoice(){setGeneratingVoice(true);setMessage("");try{const response=await fetch("/api/voiceover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:script,voice})});if(!response.ok){const data=await response.json();throw new Error(data.error||"Voiceover generation failed.")}if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl(URL.createObjectURL(await response.blob()));setMessage("Narration preview ready. The AI video will use this script as its spoken direction.")}catch(error){setMessage(error instanceof Error?error.message:"Voiceover generation failed.")}finally{setGeneratingVoice(false)}}
 async function generateVideo(){setGeneratingVideo(true);setVideoUrl("");setProgress(0);setMessage("Starting a real AI video generation job…");try{const response=await fetch("/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product,campaign,script,imageUrl:background||product.images[0]})}),data=await response.json();if(!response.ok)throw new Error(data.error||"AI video generation could not start.");setJobId(data.id);for(let attempt=0;attempt<60;attempt++){await wait(5000);const statusResponse=await fetch(`/api/video/${encodeURIComponent(data.id)}`,{cache:"no-store"}),status=await statusResponse.json();if(!statusResponse.ok)throw new Error(status.error||"Video status check failed.");setProgress(Number(status.progress||0));setMessage(status.status==="queued"?"AI video queued…":`Generating real motion footage… ${Number(status.progress||0)}%`);if(status.status==="completed"){setVideoUrl(`/api/video/${encodeURIComponent(data.id)}/content`);setProgress(100);setMessage("Real AI video completed. Preview the moving footage and download the MP4.");return}if(status.status==="failed")throw new Error(status.error||"AI video generation failed.")}throw new Error("Video generation is taking longer than expected. Please try again in a few minutes.")}catch(error){setMessage(error instanceof Error?error.message:"AI video generation failed.")}finally{setGeneratingVideo(false)}}
 function download(){if(!videoUrl)return;const link=document.createElement("a");link.href=videoUrl;link.download=`${product.handle}-ai-video.mp4`;link.click()}
 return <section className="video-production">
  <div className="video-production-heading"><div><div className="eyebrow">PHASE 9 · GENERATIVE VIDEO</div><h3><Film size={21}/> Generate real product video</h3><p>Sora creates new 9:16 moving footage from the selected reference image and sales script. This is not a photo slideshow.</p></div><span className="ai-voice-label"><Sparkles size={14}/> AI-generated video &amp; audio</span></div>
  <div className="video-script-options"><div className="script-options-heading"><strong>AI SALES SCRIPT OPTIONS</strong><span>{loadingScripts?"Improving scripts with AI…":"Choose a direction—the strongest option is selected by default."}</span></div>{options.map((option,index)=><button type="button" key={`${option.name}-${index}`} className={selected===index?"selected":""} onClick={()=>{setSelected(index);setScript(option.script);clearAssets()}}><b>{index+1}</b><span><strong>{option.name}</strong><small>{option.hook}</small></span></button>)}</div>
  <div className="video-production-grid"><div className="voiceover-editor"><label>SELECTED VIDEO SCRIPT<textarea value={script} maxLength={1600} onChange={event=>{setScript(event.target.value);setSelected(-1);clearAssets()}}/></label><div className="voice-actions"><label>NARRATION PREVIEW VOICE<select value={voice} onChange={event=>setVoice(event.target.value)}>{voices.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><button type="button" onClick={generateVoice} disabled={generatingVoice||!script.trim()}><Mic2 size={16}/>{generatingVoice?"Generating…":"Preview narration"}</button></div>{audioUrl&&<audio src={audioUrl} controls preload="metadata"/>}<button type="button" className="generate-real-video" onClick={generateVideo} disabled={generatingVideo||!script.trim()}><Sparkles size={17}/>{generatingVideo?`Generating video ${progress}%`:"Generate real AI video"}</button><small>AI video generation can take several minutes and consumes OpenAI video credits. Verify product fidelity and disclose AI-generated media where required.</small></div><div className="video-renderer">{videoUrl?<video src={videoUrl} controls playsInline/>:<div className="video-placeholder"><Play size={28}/><strong>{generatingVideo?"Generating moving footage…":"9:16 AI video preview"}</strong><span>{jobId?`Job ${jobId}`:"Select a script and generate real video."}</span></div>}<div className="video-render-actions"><button type="button" className="secondary" onClick={download} disabled={!videoUrl}><Download size={16}/>Download MP4</button></div>{generatingVideo&&<progress max="100" value={progress}/>}</div></div>{message&&<div className="status">{message}</div>}
 </section>
}
