import{randomUUID}from"crypto";import{NextRequest,NextResponse}from"next/server";import OpenAI,{toFile}from"openai";import{createSupabaseAdminClient}from"@/lib/supabase/admin";import{createSupabaseServerClient}from"@/lib/supabase/server";
const directions:Record<string,string>={luxury:"luxury UAE fashion editorial in refined architecture, warm champagne light",minimal:"minimal high-fashion studio with sculptural ivory set",studio:"polished commercial fashion studio, confident full-body pose",summer:"sunlit resort campaign, upscale summer setting","uae-lifestyle":"modern Dubai lifestyle editorial, sophisticated UAE styling",gym:"premium fitness campaign in a modern wellness studio",casual:"elevated everyday street-style campaign",resort:"five-star UAE resort editorial, golden-hour luxury","premium-black":"dramatic black fashion editorial, controlled rim lighting",editorial:"bold international fashion-magazine editorial"};
export const maxDuration=300;
export async function POST(req:NextRequest){try{if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is required for AI campaign generation.");const supabase=await createSupabaseServerClient(),{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Sign in is required."},{status:401});const{data:membership}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1).maybeSingle();if(!membership)return NextResponse.json({error:"Workspace membership is required."},{status:403});const body=await req.json(),sourceUrl=String(body.productImage||"");if(!sourceUrl)throw new Error("A Shopify product reference image is required.");const sourceResponse=await fetch(sourceUrl);if(!sourceResponse.ok)throw new Error("Unable to download the Shopify product reference image.");const type=sourceResponse.headers.get("content-type")||"image/jpeg",source=await toFile(Buffer.from(await sourceResponse.arrayBuffer()),`product.${type.includes("png")?"png":"jpg"}`,{type}),client=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),direction=directions[body.style]||directions.luxury,prompt=`Create an entirely new premium ecommerce campaign photograph using the supplied image only as the product reference.
Product: ${String(body.productTitle||"fashion product")}
Verified description: ${String(body.productDescription||"").slice(0,1200)}
Creative direction: ${direction}.
Client-requested corrections: ${String(body.corrections||"No additional corrections; create varied campaign options.").slice(0,1000)}
CRITICAL PRODUCT FIDELITY: preserve the referenced product's recognizable color, silhouette, construction, neckline, sleeves, pockets, closures, proportions, print and material appearance. Do not redesign it or add features not visible in the reference.
NEW CREATIVE: generate distinct photorealistic adult fashion models, poses, camera compositions, environments, lighting and art direction across the requested options. Every option must look newly photographed, never like the source pasted onto a background. Show the product clearly and naturally worn or carried. Premium vertical Instagram 4:5 advertising composition. Realistic anatomy, hands, fabric drape, shadows and skin. No text, logos, watermark, border, collage, duplicated person or extra product.`;const count=Math.min(5,Math.max(4,Number(body.imageCount)||4)),result=await client.images.edit({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2",image:source,prompt,size:"1024x1536",quality:"medium",n:count}),images=(result.data||[]).map(item=>item.b64_json).filter((item):item is string=>Boolean(item));if(!images.length)throw new Error("No AI campaign images were returned.");const admin=createSupabaseAdminClient(),imageUrls=await Promise.all(images.map(async image=>{const buffer=Buffer.from(image,"base64"),path=`${membership.organization_id}/ai/${new Date().toISOString().slice(0,10)}/${randomUUID()}.png`,{error:uploadError}=await admin.storage.from("campaign-assets").upload(path,buffer,{contentType:"image/png",upsert:false});if(uploadError)throw uploadError;return admin.storage.from("campaign-assets").getPublicUrl(path).data.publicUrl}));return NextResponse.json({imageUrl:imageUrls[0],imageUrls,model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2"})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to generate the campaign images."},{status:400})}}
