import{NextRequest,NextResponse}from"next/server";import OpenAI,{toFile}from"openai";
const directions:Record<string,string>={luxury:"luxury UAE fashion editorial in refined architecture, warm champagne light",minimal:"minimal high-fashion studio with sculptural ivory set",studio:"polished commercial fashion studio, confident full-body pose",summer:"sunlit resort campaign, upscale summer setting","uae-lifestyle":"modern Dubai lifestyle editorial, sophisticated UAE styling",gym:"premium fitness campaign in a modern wellness studio",casual:"elevated everyday street-style campaign",resort:"five-star UAE resort editorial, golden-hour luxury","premium-black":"dramatic black fashion editorial, controlled rim lighting",editorial:"bold international fashion-magazine editorial"};
export const maxDuration=60;
export async function POST(req:NextRequest){try{if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is required for AI campaign generation.");const body=await req.json(),sourceUrl=String(body.productImage||"");if(!sourceUrl)throw new Error("A Shopify product reference image is required.");const sourceResponse=await fetch(sourceUrl);if(!sourceResponse.ok)throw new Error("Unable to download the Shopify product reference image.");const type=sourceResponse.headers.get("content-type")||"image/jpeg",source=await toFile(Buffer.from(await sourceResponse.arrayBuffer()),`product.${type.includes("png")?"png":"jpg"}`,{type}),client=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),direction=directions[body.style]||directions.luxury,prompt=`Create an entirely new premium ecommerce campaign photograph using the supplied image only as the product reference.
Product: ${String(body.productTitle||"fashion product")}
Verified description: ${String(body.productDescription||"").slice(0,1200)}
Creative direction: ${direction}.
CRITICAL PRODUCT FIDELITY: preserve the referenced product's recognizable color, silhouette, construction, neckline, sleeves, pockets, closures, proportions, print and material appearance. Do not redesign it or add features not visible in the reference.
NEW CREATIVE: generate a new photorealistic adult fashion model, clearly different pose, camera composition, environment, lighting and art direction. This must look newly photographed, never like the source pasted onto a background. Show the product clearly and naturally worn or carried. Premium vertical Instagram 4:5 advertising composition. Realistic anatomy, hands, fabric drape, shadows and skin. No text, logos, watermark, border, collage, duplicated person or extra product.`;const result=await client.images.edit({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2",image:source,prompt,size:"1024x1536",quality:"medium"}),image=result.data?.[0]?.b64_json;if(!image)throw new Error("No AI campaign image was returned.");return NextResponse.json({dataUrl:`data:image/png;base64,${image}`,model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2"})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to generate the campaign image."},{status:400})}}
